/** Don't Say It cards: describe `w` without saying it or any word in `ban`. 90% Indian, 10% famous everywhere (`g: 1`). */
export type Card = { w: string; ban: [string, string, string, string]; g?: 1 };

export const CARDS: Card[] = [
	// festivals
	{ w: "Diwali", ban: ["Lights", "Festival", "Crackers", "Diya"] },
	{ w: "Holi", ban: ["Colours", "Gulal", "Pichkari", "Water balloons"] },
	{ w: "Raksha Bandhan", ban: ["Rakhi", "Brother", "Sister", "Thread"] },
	{ w: "Eid", ban: ["Moon", "Ramzan", "Sevaiyan", "Mubarak"] },
	{ w: "Christmas", ban: ["Santa", "December", "Tree", "Gifts"] },
	{ w: "Pongal", ban: ["Tamil", "Harvest", "Sugarcane", "January"] },
	{ w: "Navratri", ban: ["Nine nights", "Garba", "Dandiya", "Durga"] },
	{ w: "Ganesh Chaturthi", ban: ["Ganpati", "Modak", "Elephant", "Visarjan"] },
	{ w: "Durga Puja", ban: ["Kolkata", "Pandal", "Goddess", "Bengali"] },
	{ w: "Onam", ban: ["Kerala", "Pookalam", "Sadya", "Boat race"] },
	{ w: "Lohri", ban: ["Bonfire", "Punjab", "January", "Winter"] },
	{ w: "Makar Sankranti", ban: ["Kites", "January", "Til", "Uttarayan"] },
	{ w: "Baisakhi", ban: ["Punjab", "Harvest", "Bhangra", "April"] },
	{ w: "Independence Day", ban: ["August", "Flag", "Freedom", "Fifteenth"] },
	{ w: "Rangoli", ban: ["Colours", "Floor", "Design", "Diwali"] },
	{ w: "Garba", ban: ["Dandiya", "Navratri", "Gujarat", "Dance"] },

	// food
	{ w: "Chai", ban: ["Tea", "Milk", "Cutting", "Adrak"] },
	{ w: "Samosa", ban: ["Aloo", "Triangle", "Fried", "Chutney"] },
	{ w: "Biryani", ban: ["Rice", "Hyderabad", "Chicken", "Dum"] },
	{ w: "Pani Puri", ban: ["Golgappa", "Puchka", "Tangy water", "Chaat"] },
	{ w: "Dosa", ban: ["South Indian", "Crispy", "Sambar", "Masala"] },
	{ w: "Maggi", ban: ["Noodles", "Two minutes", "Instant", "Hostel"] },
	{ w: "Idli", ban: ["Steamed", "Sambar", "South Indian", "Rice cake"] },
	{ w: "Vada Pav", ban: ["Mumbai", "Burger", "Potato", "Bun"] },
	{ w: "Jalebi", ban: ["Sweet", "Orange", "Spiral", "Syrup"] },
	{ w: "Gulab Jamun", ban: ["Sweet", "Brown", "Syrup", "Round"] },
	{ w: "Butter Chicken", ban: ["Punjabi", "Gravy", "Naan", "Creamy"] },
	{ w: "Paneer", ban: ["Cheese", "Cottage", "Tikka", "White"] },
	{ w: "Rasgulla", ban: ["Bengali", "Sweet", "Spongy", "Syrup"] },
	{ w: "Chole Bhature", ban: ["Chickpeas", "Fried", "Delhi", "Punjabi"] },
	{ w: "Pav Bhaji", ban: ["Mumbai", "Butter", "Bread", "Vegetables"] },
	{ w: "Khichdi", ban: ["Rice", "Dal", "Sick", "Simple"] },
	{ w: "Lassi", ban: ["Curd", "Punjab", "Glass", "Sweet"] },
	{ w: "Momos", ban: ["Dumplings", "Steamed", "Tibetan", "Red chutney"] },
	{ w: "Ladoo", ban: ["Sweet", "Round", "Besan", "Motichoor"] },
	{ w: "Poha", ban: ["Breakfast", "Flattened rice", "Indore", "Yellow"] },
	{ w: "Paratha", ban: ["Aloo", "Butter", "Stuffed", "Tawa"] },
	{ w: "Pickle", ban: ["Achaar", "Mango", "Oil", "Jar"] },
	{ w: "Kulfi", ban: ["Ice cream", "Stick", "Frozen", "Matka"] },
	{ w: "Mango", ban: ["Fruit", "Summer", "Alphonso", "Aam"] },
	{ w: "Coconut", ban: ["Water", "Tree", "Kerala", "Shell"] },
	{ w: "Filter Coffee", ban: ["South Indian", "Tumbler", "Decoction", "Chennai"] },
	{ w: "Dhokla", ban: ["Gujarati", "Yellow", "Steamed", "Spongy"] },
	{ w: "Rajma Chawal", ban: ["Kidney beans", "Rice", "Punjabi", "Sunday"] },
	{ w: "Thali", ban: ["Plate", "Steel", "Unlimited", "Katori"] },
	{ w: "Pakora", ban: ["Rain", "Fried", "Besan", "Onion"] },
	{ w: "Parle-G", ban: ["Biscuit", "Glucose", "Chai", "Girl"] },
	{ w: "Paan", ban: ["Leaf", "Betel", "Banaras", "Mouth freshener"] },

	// places
	{ w: "Taj Mahal", ban: ["Agra", "Shah Jahan", "White marble", "Wonder"] },
	{ w: "Goa", ban: ["Beach", "Party", "Portuguese", "Vacation"] },
	{ w: "Mumbai Local", ban: ["Train", "Crowd", "Station", "Dadar"] },
	{ w: "Ladakh", ban: ["Mountains", "Bike trip", "Pangong", "Leh"] },
	{ w: "Kerala", ban: ["Backwaters", "Houseboat", "Coconut", "Onam"] },
	{ w: "Manali", ban: ["Himachal", "Snow", "Hill station", "Rohtang"] },
	{ w: "Rajasthan", ban: ["Desert", "Camel", "Jaipur", "Forts"] },
	{ w: "Gateway of India", ban: ["Mumbai", "Arch", "Sea", "Taj Hotel"] },
	{ w: "India Gate", ban: ["Delhi", "War memorial", "Arch", "Republic Day"] },
	{ w: "Himalayas", ban: ["Mountains", "Everest", "Snow", "Range"] },
	{ w: "Varanasi", ban: ["Ghats", "Ganga", "Banaras", "Aarti"] },
	{ w: "Marine Drive", ban: ["Mumbai", "Queen's Necklace", "Sea", "Evening walk"] },
	{ w: "Bangalore", ban: ["Traffic", "IT", "Silicon Valley", "Karnataka"] },
	{ w: "Delhi", ban: ["Capital", "India Gate", "Chandni Chowk", "Metro"] },
	{ w: "Kolkata", ban: ["Bengal", "Howrah", "Rasgulla", "Yellow taxi"] },
	{ w: "Hyderabad", ban: ["Biryani", "Charminar", "Nizam", "Telangana"] },
	{ w: "Chennai", ban: ["Tamil", "Marina", "Madras", "Filter coffee"] },
	{ w: "Darjeeling", ban: ["Tea", "Toy train", "Hills", "Bengal"] },

	// cricket and sport
	{ w: "Cricket", ban: ["Bat", "Ball", "Wicket", "Sachin"] },
	{ w: "IPL", ban: ["Cricket", "T20", "Auction", "Teams"] },
	{ w: "Sachin Tendulkar", ban: ["Master Blaster", "Cricket", "Mumbai", "Hundred"] },
	{ w: "MS Dhoni", ban: ["Captain Cool", "Helicopter shot", "Ranchi", "CSK"] },
	{ w: "Virat Kohli", ban: ["RCB", "Anushka", "Captain", "Cricket"] },
	{ w: "Sixer", ban: ["Boundary", "Runs", "Maximum", "Stands"] },
	{ w: "Wicket", ban: ["Stumps", "Out", "Bowler", "Bails"] },
	{ w: "Umpire", ban: ["Referee", "Finger", "Out", "Decision"] },
	{ w: "Hat-trick", ban: ["Three", "Wickets", "Bowler", "Consecutive"] },
	{ w: "Gully Cricket", ban: ["Street", "Tennis ball", "Bat", "Neighbours"] },
	{ w: "Toss", ban: ["Coin", "Heads", "Tails", "Captain"] },
	{ w: "Kapil Dev", ban: ["1983", "World Cup", "Captain", "Haryana"] },
	{ w: "Kabaddi", ban: ["Raid", "Touch", "Breath", "Pro league"] },

	// bollywood and tv
	{ w: "Mogambo", ban: ["Mr India", "Villain", "Khush hua", "Amrish Puri"] },
	{ w: "Interval", ban: ["Break", "Samosa", "Popcorn", "Half"] },
	{ w: "Villain", ban: ["Bad guy", "Hero", "Evil", "Gabbar"] },
	{ w: "Big B", ban: ["Amitabh", "Bachchan", "KBC", "Shahenshah"] },
	{ w: "Shah Rukh Khan", ban: ["SRK", "King", "Mannat", "DDLJ"] },
	{ w: "Salman Khan", ban: ["Bhai", "Dabangg", "Being Human", "Tiger"] },
	{ w: "Sholay", ban: ["Gabbar", "Jai Veeru", "Basanti", "Thakur"] },
	{ w: "DDLJ", ban: ["Shah Rukh", "Kajol", "Train", "Mustard fields"] },
	{ w: "Bollywood", ban: ["Hindi", "Movies", "Mumbai", "Film industry"] },
	{ w: "Rajinikanth", ban: ["Thalaivar", "Superstar", "Sunglasses", "Tamil"] },
	{ w: "Hero Entry", ban: ["Slow motion", "Whistles", "Film", "Grand"] },
	{ w: "KBC", ban: ["Quiz", "Amitabh", "Crorepati", "Lifeline"] },
	{ w: "Bigg Boss", ban: ["Reality show", "House", "Salman", "Eviction"] },
	{ w: "Lagaan", ban: ["Aamir", "Cricket", "Tax", "Oscar"] },
	{ w: "3 Idiots", ban: ["Aamir", "Engineering", "Rancho", "College"] },
	{ w: "Baahubali", ban: ["Prabhas", "Kattappa", "Rajamouli", "Mahishmati"] },
	{ w: "Antakshari", ban: ["Songs", "Last letter", "Game", "Singing"] },
	{ w: "Lata Mangeshkar", ban: ["Singer", "Nightingale", "Asha Bhosle", "Voice"] },
	{ w: "Priyanka Chopra", ban: ["Desi girl", "Nick Jonas", "Hollywood", "Miss World"] },
	{ w: "Box Office", ban: ["Collection", "Crore", "Tickets", "Hit"] },
	{ w: "Doordarshan", ban: ["TV", "Channel", "Old", "Antenna"] },

	// animals
	{ w: "Elephant", ban: ["Trunk", "Big", "Grey", "Tusks"] },
	{ w: "Tiger", ban: ["Stripes", "National animal", "Jungle", "Roar"] },
	{ w: "Peacock", ban: ["Feathers", "National bird", "Dance", "Blue"] },
	{ w: "Cow", ban: ["Milk", "Moo", "Horns", "Farm"] },
	{ w: "Monkey", ban: ["Banana", "Tail", "Jump", "Tree"] },
	{ w: "Street Dog", ban: ["Bark", "Stray", "Road", "Puppy"] },
	{ w: "Camel", ban: ["Desert", "Hump", "Rajasthan", "Ride"] },
	{ w: "Parrot", ban: ["Green", "Talk", "Bird", "Mirchi"] },
	{ w: "Cobra", ban: ["Snake", "Charmer", "Poison", "Hood"] },
	{ w: "Crow", ban: ["Black", "Bird", "Caw", "Kauwa"] },
	{ w: "Lizard", ban: ["Wall", "Chipkali", "Tail", "Scream"] },
	{ w: "Cockroach", ban: ["Insect", "Kitchen", "Scream", "Brown"] },
	{ w: "Owl", ban: ["Night", "Bird", "Ullu", "Hoot"] },
	{ w: "Pigeon", ban: ["Bird", "Grey", "Kabootar", "Balcony"] },

	// jobs
	{ w: "Engineer", ban: ["IIT", "Software", "Degree", "Kota"] },
	{ w: "Doctor", ban: ["Hospital", "Stethoscope", "Medicine", "Patient"] },
	{ w: "Watchman", ban: ["Guard", "Gate", "Night", "Building"] },
	{ w: "Barber", ban: ["Hair", "Haircut", "Salon", "Scissors"] },
	{ w: "Postman", ban: ["Letters", "Mail", "Khaki", "Delivery"] },
	{ w: "Traffic Police", ban: ["Whistle", "Signal", "Challan", "Uniform"] },
	{ w: "Teacher", ban: ["School", "Class", "Blackboard", "Students"] },
	{ w: "Tailor", ban: ["Stitch", "Clothes", "Darzi", "Measure"] },
	{ w: "Delivery Boy", ban: ["Swiggy", "Zomato", "Food", "Bike"] },
	{ w: "Farmer", ban: ["Fields", "Crops", "Tractor", "Village"] },
	{ w: "Dhobi", ban: ["Clothes", "Iron", "Washing", "Laundry"] },
	{ w: "Sabziwala", ban: ["Vegetables", "Cart", "Dhaniya", "Haggling"] },

	// daily life
	{ w: "Auto Rickshaw", ban: ["Three wheeler", "Meter", "Driver", "Tuk tuk"] },
	{ w: "Traffic Jam", ban: ["Cars", "Horn", "Stuck", "Road"] },
	{ w: "Power Cut", ban: ["Electricity", "Light", "Inverter", "Dark"] },
	{ w: "Pressure Cooker", ban: ["Whistle", "Kitchen", "Steam", "Dal"] },
	{ w: "WhatsApp Forward", ban: ["Message", "Uncle", "Good morning", "Fake news"] },
	{ w: "Mehendi", ban: ["Henna", "Hands", "Design", "Wedding"] },
	{ w: "Shaadi", ban: ["Wedding", "Marriage", "Bride", "Groom"] },
	{ w: "Board Exams", ban: ["Tenth", "Twelfth", "CBSE", "Marks"] },
	{ w: "Tiffin", ban: ["Lunch box", "School", "Office", "Dabba"] },
	{ w: "Mosquito", ban: ["Bite", "Dengue", "Buzz", "Net"] },
	{ w: "Monsoon", ban: ["Rain", "Umbrella", "July", "Clouds"] },
	{ w: "Umbrella", ban: ["Rain", "Chhatri", "Open", "Wet"] },
	{ w: "Cooler", ban: ["Summer", "Water", "Fan", "Air"] },
	{ w: "Ceiling Fan", ban: ["Spin", "Blades", "Summer", "Switch"] },
	{ w: "Inverter", ban: ["Battery", "Power cut", "Backup", "Electricity"] },
	{ w: "Dabbawala", ban: ["Mumbai", "Lunch", "Tiffin", "Delivery"] },
	{ w: "Kirana Store", ban: ["Shop", "Grocery", "Uncle", "Corner"] },
	{ w: "Bargaining", ban: ["Price", "Discount", "Shopkeeper", "Haggling"] },
	{ w: "Jugaad", ban: ["Hack", "Fix", "Creative", "Solution"] },
	{ w: "Sharma ji ka beta", ban: ["Neighbour", "Topper", "Comparison", "Perfect"] },
	{ w: "Tatkal", ban: ["Ticket", "Train", "Booking", "IRCTC"] },
	{ w: "Metro", ban: ["Train", "Delhi", "Underground", "Card"] },
	{ w: "Scooter", ban: ["Activa", "Two wheeler", "Helmet", "Kick"] },
	{ w: "Pothole", ban: ["Road", "Rain", "Bump", "Crater"] },
	{ w: "Speed Breaker", ban: ["Bump", "Road", "Slow", "Car"] },
	{ w: "Joint Family", ban: ["Relatives", "Grandparents", "Together", "House"] },
	{ w: "UPI", ban: ["Payment", "PhonePe", "QR code", "Paytm"] },
	{ w: "Toll Plaza", ban: ["Highway", "FASTag", "Pay", "Booth"] },
	{ w: "Baraat", ban: ["Wedding", "Horse", "Dance", "Groom"] },
	{ w: "Sangeet", ban: ["Wedding", "Dance", "Songs", "Night"] },
	{ w: "Dhol", ban: ["Drum", "Punjabi", "Beat", "Wedding"] },
	{ w: "Kite", ban: ["Fly", "String", "Manja", "Sankranti"] },
	{ w: "Carrom", ban: ["Board", "Striker", "Queen", "Powder"] },
	{ w: "Ludo", ban: ["Dice", "Board game", "Tokens", "Six"] },
	{ w: "Mixer Grinder", ban: ["Kitchen", "Blender", "Chutney", "Noise"] },
	{ w: "Tawa", ban: ["Pan", "Roti", "Iron", "Flat"] },
	{ w: "Chappal", ban: ["Slippers", "Feet", "Mummy", "Rubber"] },
	{ w: "Kurta", ban: ["Shirt", "Long", "Pyjama", "Ethnic"] },
	{ w: "Saree", ban: ["Drape", "Six yards", "Silk", "Blouse"] },
	{ w: "Bindi", ban: ["Forehead", "Dot", "Red", "Sticker"] },
	{ w: "Bangles", ban: ["Wrist", "Glass", "Churi", "Jingle"] },
	{ w: "Alarm Clock", ban: ["Wake up", "Morning", "Snooze", "Ring"] },
	{ w: "Tuition", ban: ["Classes", "Teacher", "Coaching", "Study"] },
	{ w: "Hostel", ban: ["College", "Room", "Mess", "Warden"] },
	{ w: "Canteen", ban: ["College", "Food", "Samosa", "Cheap"] },
	{ w: "Yoga", ban: ["Exercise", "Asana", "Stretch", "Mat"] },
	{ w: "Rupee", ban: ["Money", "Currency", "Note", "Coin"] },
	{ w: "Chandrayaan", ban: ["Moon", "ISRO", "Rocket", "Mission"] },
	{ w: "Nimbu Mirchi", ban: ["Lemon", "Chilli", "Evil eye", "Hang"] },
	{ w: "Moustache", ban: ["Mooch", "Beard", "Upper lip", "Twirl"] },
	{ w: "Dhaba", ban: ["Highway", "Truck", "Food", "Charpai"] },
	{ w: "Charpai", ban: ["Bed", "Rope", "Village", "Dhaba"] },
	{ w: "Matka", ban: ["Pot", "Clay", "Water", "Cool"] },
	{ w: "Almirah", ban: ["Cupboard", "Steel", "Locker", "Clothes"] },
	{ w: "Bucket", ban: ["Water", "Bath", "Mug", "Plastic"] },
	{ w: "Remote Control", ban: ["TV", "Buttons", "Channel", "Battery"] },

	// famous everywhere
	{ w: "Pizza", ban: ["Cheese", "Italian", "Slice", "Domino's"], g: 1 },
	{ w: "Eiffel Tower", ban: ["Paris", "France", "Iron", "Tall"], g: 1 },
	{ w: "Harry Potter", ban: ["Wizard", "Hogwarts", "Magic", "Scar"], g: 1 },
	{ w: "Football World Cup", ban: ["FIFA", "Messi", "Goal", "Trophy"], g: 1 },
	{ w: "Instagram", ban: ["Reels", "Photos", "Stories", "Followers"], g: 1 },
	{ w: "Titanic", ban: ["Ship", "Iceberg", "Jack", "Rose"], g: 1 },
	{ w: "Mickey Mouse", ban: ["Disney", "Cartoon", "Ears", "Minnie"], g: 1 },
	{ w: "Netflix", ban: ["Streaming", "Series", "Binge", "Subscription"], g: 1 },
	{ w: "Burger", ban: ["Bun", "Patty", "McDonald's", "Fast food"], g: 1 },
	{ w: "Spider-Man", ban: ["Web", "Superhero", "Marvel", "Peter Parker"], g: 1 },
	{ w: "Olympics", ban: ["Medal", "Rings", "Gold", "Games"], g: 1 },
	{ w: "Chocolate", ban: ["Cocoa", "Sweet", "Brown", "Cadbury"], g: 1 },
	{ w: "Selfie", ban: ["Photo", "Phone", "Front camera", "Pout"], g: 1 },
	{ w: "Mount Everest", ban: ["Tallest", "Himalayas", "Climb", "Nepal"], g: 1 },
	{ w: "Google", ban: ["Search", "Internet", "Browser", "Android"], g: 1 },
	{ w: "Santa Claus", ban: ["Christmas", "Beard", "Gifts", "Red"], g: 1 },
	{ w: "YouTube", ban: ["Videos", "Subscribe", "Channel", "Watch"], g: 1 },
	{ w: "Statue of Liberty", ban: ["New York", "America", "Torch", "Green"], g: 1 },
	{ w: "Popcorn", ban: ["Movies", "Butter", "Salted", "Tub"], g: 1 },
	{ w: "Tom and Jerry", ban: ["Cat", "Mouse", "Cartoon", "Chase"], g: 1 },
];
