/** Movies for Dumb Charades and Emoji Movie: 90% Indian, 10% famous everywhere. `g: 1` marks non-Indian. */
export type Movie = { t: string; tag: "Bollywood" | "South" | "Hollywood"; aka?: string[]; g?: 1 };

export const MOVIES: Movie[] = [
	// Classics
	{ t: "Mother India", tag: "Bollywood" },
	{ t: "Mughal-e-Azam", tag: "Bollywood" },
	{ t: "Awaara", tag: "Bollywood", aka: ["Awara"] },
	{ t: "Shree 420", tag: "Bollywood", aka: ["Shri 420", "Shree Four Twenty"] },
	{ t: "Pyaasa", tag: "Bollywood", aka: ["Pyasa"] },
	{ t: "Chalti Ka Naam Gaadi", tag: "Bollywood", aka: ["Chalti Ka Naam Gadi"] },
	{ t: "Sangam", tag: "Bollywood" },
	{ t: "Guide", tag: "Bollywood" },
	{ t: "Padosan", tag: "Bollywood" },
	{ t: "Aradhana", tag: "Bollywood" },
	{ t: "Mera Naam Joker", tag: "Bollywood" },
	{ t: "Anand", tag: "Bollywood" },
	{ t: "Pakeezah", tag: "Bollywood", aka: ["Pakeeza"] },
	{ t: "Seeta Aur Geeta", tag: "Bollywood", aka: ["Sita Aur Gita"] },
	{ t: "Bobby", tag: "Bollywood" },
	{ t: "Zanjeer", tag: "Bollywood", aka: ["Zanjir"] },
	{ t: "Yaadon Ki Baaraat", tag: "Bollywood", aka: ["Yaadon Ki Baraat"] },
	{ t: "Roti Kapda Aur Makaan", tag: "Bollywood", aka: ["Roti Kapda Aur Makan"] },
	{ t: "Deewaar", tag: "Bollywood", aka: ["Deewar"] },
	{ t: "Sholay", tag: "Bollywood" },
	{ t: "Chupke Chupke", tag: "Bollywood" },
	{ t: "Kabhi Kabhie", tag: "Bollywood", aka: ["Kabhi Kabhi"] },
	{ t: "Amar Akbar Anthony", tag: "Bollywood" },
	{ t: "Hum Kisise Kum Naheen", tag: "Bollywood", aka: ["Hum Kisi Se Kum Nahin"] },
	{ t: "Don", tag: "Bollywood" },
	{ t: "Trishul", tag: "Bollywood", aka: ["Trishool"] },
	{ t: "Muqaddar Ka Sikandar", tag: "Bollywood", aka: ["Muqaddar Ka Sikander"] },
	{ t: "Golmaal", tag: "Bollywood" },

	// 80s
	{ t: "Karz", tag: "Bollywood" },
	{ t: "Chashme Buddoor", tag: "Bollywood", aka: ["Chashme Baddoor"] },
	{ t: "Satte Pe Satta", tag: "Bollywood" },
	{ t: "Namak Halaal", tag: "Bollywood", aka: ["Namak Halal"] },
	{ t: "Disco Dancer", tag: "Bollywood" },
	{ t: "Angoor", tag: "Bollywood" },
	{ t: "Coolie", tag: "Bollywood" },
	{ t: "Masoom", tag: "Bollywood" },
	{ t: "Jaane Bhi Do Yaaro", tag: "Bollywood", aka: ["Jaane Bhi Do Yaro"] },
	{ t: "Himmatwala", tag: "Bollywood" },
	{ t: "Mr. India", tag: "Bollywood", aka: ["Mister India"] },
	{ t: "Nagina", tag: "Bollywood" },
	{ t: "Qayamat Se Qayamat Tak", tag: "Bollywood", aka: ["QSQT"] },
	{ t: "Shahenshah", tag: "Bollywood" },
	{ t: "Chandni", tag: "Bollywood", aka: ["Chaandni"] },
	{ t: "Maine Pyar Kiya", tag: "Bollywood", aka: ["Maine Pyaar Kiya"] },
	{ t: "Ram Lakhan", tag: "Bollywood" },

	// 90s
	{ t: "Dil", tag: "Bollywood" },
	{ t: "Aashiqui", tag: "Bollywood", aka: ["Ashiqui"] },
	{ t: "Hum", tag: "Bollywood" },
	{ t: "Saajan", tag: "Bollywood", aka: ["Sajan"] },
	{ t: "Dil Hai Ki Manta Nahin", tag: "Bollywood", aka: ["Dil Hai Ke Manta Nahin"] },
	{ t: "Beta", tag: "Bollywood" },
	{ t: "Deewana", tag: "Bollywood", aka: ["Diwana"] },
	{ t: "Jo Jeeta Wohi Sikandar", tag: "Bollywood", aka: ["Jo Jeeta Wahi Sikandar"] },
	{ t: "Hum Hain Rahi Pyar Ke", tag: "Bollywood", aka: ["Hum Hain Raahi Pyar Ke"] },
	{ t: "Hum Aapke Hain Koun", tag: "Bollywood", aka: ["HAHK", "Hum Aapke Hain Kaun"] },
	{ t: "Andaz Apna Apna", tag: "Bollywood", aka: ["Andaaz Apna Apna"] },
	{ t: "Kabhi Haan Kabhi Naa", tag: "Bollywood", aka: ["Kabhi Haan Kabhi Na"] },
	{ t: "Karan Arjun", tag: "Bollywood" },
	{ t: "Dilwale Dulhania Le Jayenge", tag: "Bollywood", aka: ["DDLJ", "Dilwale Dulhaniya Le Jayenge"] },
	{ t: "Rangeela", tag: "Bollywood" },
	{ t: "Coolie No. 1", tag: "Bollywood", aka: ["Coolie Number 1", "Coolie Number One"] },
	{ t: "Raja Hindustani", tag: "Bollywood" },
	{ t: "Dil To Pagal Hai", tag: "Bollywood" },
	{ t: "Judwaa", tag: "Bollywood", aka: ["Judwa"] },
	{ t: "Ishq", tag: "Bollywood" },
	{ t: "Pardes", tag: "Bollywood" },
	{ t: "Yes Boss", tag: "Bollywood" },
	{ t: "Kuch Kuch Hota Hai", tag: "Bollywood", aka: ["KKHH"] },
	{ t: "Bade Miyan Chote Miyan", tag: "Bollywood" },
	{ t: "Hero No. 1", tag: "Bollywood", aka: ["Hero Number 1", "Hero Number One"] },
	{ t: "Biwi No. 1", tag: "Bollywood", aka: ["Biwi Number 1", "Biwi Number One"] },
	{ t: "Sooryavansham", tag: "Bollywood", aka: ["Suryavansham"] },
	{ t: "Hum Dil De Chuke Sanam", tag: "Bollywood", aka: ["HDDCS"] },
	{ t: "Taal", tag: "Bollywood" },
	{ t: "Hum Saath-Saath Hain", tag: "Bollywood" },
	{ t: "Chachi 420", tag: "Bollywood", aka: ["Chachi Four Twenty"] },

	// 2000s
	{ t: "Race", tag: "Bollywood" },
	{ t: "Mohabbatein", tag: "Bollywood" },
	{ t: "Hera Pheri", tag: "Bollywood", aka: ["Hera Feri"] },
	{ t: "Dhadkan", tag: "Bollywood" },
	{ t: "Phir Bhi Dil Hai Hindustani", tag: "Bollywood" },
	{ t: "Lagaan", tag: "Bollywood" },
	{ t: "Dil Chahta Hai", tag: "Bollywood" },
	{ t: "Gadar: Ek Prem Katha", tag: "Bollywood", aka: ["Gadar"] },
	{ t: "Kabhi Khushi Kabhie Gham", tag: "Bollywood", aka: ["K3G", "Kabhi Khushi Kabhi Gham"] },
	{ t: "Nayak", tag: "Bollywood" },
	{ t: "Devdas", tag: "Bollywood" },
	{ t: "Hungama", tag: "Bollywood" },
	{ t: "Koi Mil Gaya", tag: "Bollywood" },
	{ t: "Kal Ho Naa Ho", tag: "Bollywood", aka: ["KHNH", "Kal Ho Na Ho"] },
	{ t: "Munna Bhai MBBS", tag: "Bollywood", aka: ["Munna Bhai"] },
	{ t: "Baghban", tag: "Bollywood", aka: ["Baghbaan"] },
	{ t: "Chalte Chalte", tag: "Bollywood" },
	{ t: "Main Hoon Na", tag: "Bollywood" },
	{ t: "Hum Tum", tag: "Bollywood" },
	{ t: "Dhoom", tag: "Bollywood" },
	{ t: "Veer-Zaara", tag: "Bollywood", aka: ["Veer Zara"] },
	{ t: "Swades", tag: "Bollywood" },
	{ t: "Hulchul", tag: "Bollywood", aka: ["Hulchal"] },
	{ t: "Bunty Aur Babli", tag: "Bollywood" },
	{ t: "No Entry", tag: "Bollywood" },
	{ t: "Garam Masala", tag: "Bollywood" },
	{ t: "Parineeta", tag: "Bollywood" },
	{ t: "Iqbal", tag: "Bollywood" },
	{ t: "Rang De Basanti", tag: "Bollywood", aka: ["RDB"] },
	{ t: "Krrish", tag: "Bollywood", aka: ["Krish"] },
	{ t: "Lage Raho Munna Bhai", tag: "Bollywood" },
	{ t: "Dhoom 2", tag: "Bollywood", aka: ["Dhoom Two"] },
	{ t: "Phir Hera Pheri", tag: "Bollywood", aka: ["Phir Hera Feri"] },
	{ t: "Malamaal Weekly", tag: "Bollywood" },
	{ t: "Vivah", tag: "Bollywood" },
	{ t: "Bhagam Bhag", tag: "Bollywood" },
	{ t: "Guru", tag: "Bollywood" },
	{ t: "Namastey London", tag: "Bollywood", aka: ["Namaste London"] },
	{ t: "Partner", tag: "Bollywood" },
	{ t: "Heyy Babyy", tag: "Bollywood", aka: ["Hey Baby"] },
	{ t: "Dhamaal", tag: "Bollywood" },
	{ t: "Chak De! India", tag: "Bollywood", aka: ["Chak De"] },
	{ t: "Om Shanti Om", tag: "Bollywood" },
	{ t: "Taare Zameen Par", tag: "Bollywood", aka: ["Tare Zameen Par"] },
	{ t: "Jab We Met", tag: "Bollywood" },
	{ t: "Bhool Bhulaiyaa", tag: "Bollywood", aka: ["Bhool Bhulaiya"] },
	{ t: "Welcome", tag: "Bollywood" },
	{ t: "Bhoothnath", tag: "Bollywood", aka: ["Bhootnath"] },
	{ t: "Jodhaa Akbar", tag: "Bollywood", aka: ["Jodha Akbar"] },
	{ t: "Rock On!!", tag: "Bollywood" },
	{ t: "Jaane Tu... Ya Jaane Na", tag: "Bollywood", aka: ["Jane Tu Ya Jane Na"] },
	{ t: "Singh Is Kinng", tag: "Bollywood", aka: ["Singh Is King"] },
	{ t: "Rab Ne Bana Di Jodi", tag: "Bollywood", aka: ["RNBDJ"] },
	{ t: "3 Idiots", tag: "Bollywood", aka: ["Three Idiots"] },
	{ t: "Wake Up Sid", tag: "Bollywood" },
	{ t: "Ajab Prem Ki Ghazab Kahani", tag: "Bollywood" },
	{ t: "Love Aaj Kal", tag: "Bollywood" },
	{ t: "Paa", tag: "Bollywood" },

	// 2010s
	{ t: "My Name Is Khan", tag: "Bollywood" },
	{ t: "Dabangg", tag: "Bollywood", aka: ["Dabang"] },
	{ t: "Housefull", tag: "Bollywood" },
	{ t: "Band Baaja Baaraat", tag: "Bollywood", aka: ["Band Baja Baraat"] },
	{ t: "Tanu Weds Manu", tag: "Bollywood" },
	{ t: "Yamla Pagla Deewana", tag: "Bollywood", aka: ["Yamla Pagla Diwana"] },
	{ t: "Zindagi Na Milegi Dobara", tag: "Bollywood", aka: ["ZNMD", "Zindagi Naa Milegi Dobara"] },
	{ t: "Ready", tag: "Bollywood" },
	{ t: "Bodyguard", tag: "Bollywood" },
	{ t: "Rockstar", tag: "Bollywood" },
	{ t: "Ra.One", tag: "Bollywood" },
	{ t: "Singham", tag: "Bollywood" },
	{ t: "Barfi!", tag: "Bollywood" },
	{ t: "Ek Tha Tiger", tag: "Bollywood" },
	{ t: "Bol Bachchan", tag: "Bollywood" },
	{ t: "English Vinglish", tag: "Bollywood" },
	{ t: "Kahaani", tag: "Bollywood", aka: ["Kahani"] },
	{ t: "OMG: Oh My God!", tag: "Bollywood", aka: ["OMG", "Oh My God"] },
	{ t: "Jab Tak Hai Jaan", tag: "Bollywood" },
	{ t: "Student of the Year", tag: "Bollywood", aka: ["SOTY"] },
	{ t: "Jolly LLB", tag: "Bollywood" },
	{ t: "Aashiqui 2", tag: "Bollywood", aka: ["Aashiqui Two", "Ashiqui 2"] },
	{ t: "Yeh Jawaani Hai Deewani", tag: "Bollywood", aka: ["YJHD", "Yeh Jawani Hai Deewani"] },
	{ t: "Chennai Express", tag: "Bollywood" },
	{ t: "Fukrey", tag: "Bollywood" },
	{ t: "Krrish 3", tag: "Bollywood", aka: ["Krish 3", "Krrish Three"] },
	{ t: "Dhoom 3", tag: "Bollywood", aka: ["Dhoom Three"] },
	{ t: "Bhaag Milkha Bhaag", tag: "Bollywood", aka: ["Bhag Milkha Bhag"] },
	{ t: "Queen", tag: "Bollywood" },
	{ t: "2 States", tag: "Bollywood", aka: ["Two States"] },
	{ t: "Humpty Sharma Ki Dulhania", tag: "Bollywood" },
	{ t: "Kick", tag: "Bollywood" },
	{ t: "PK", tag: "Bollywood" },
	{ t: "Happy New Year", tag: "Bollywood" },
	{ t: "Mary Kom", tag: "Bollywood" },
	{ t: "Piku", tag: "Bollywood" },
	{ t: "Bajrangi Bhaijaan", tag: "Bollywood", aka: ["Bajrangi Bhaijan"] },
	{ t: "Dil Dhadakne Do", tag: "Bollywood" },
	{ t: "Prem Ratan Dhan Payo", tag: "Bollywood", aka: ["PRDP"] },
	{ t: "Bajirao Mastani", tag: "Bollywood" },
	{ t: "Dilwale", tag: "Bollywood" },
	{ t: "Dangal", tag: "Bollywood" },
	{ t: "Sultan", tag: "Bollywood" },
	{ t: "Dear Zindagi", tag: "Bollywood" },
	{ t: "M.S. Dhoni: The Untold Story", tag: "Bollywood", aka: ["MS Dhoni", "Dhoni"] },
	{ t: "Badrinath Ki Dulhania", tag: "Bollywood" },
	{ t: "Hindi Medium", tag: "Bollywood" },
	{ t: "Bareilly Ki Barfi", tag: "Bollywood" },
	{ t: "Secret Superstar", tag: "Bollywood" },
	{ t: "Golmaal Again", tag: "Bollywood" },
	{ t: "Stree", tag: "Bollywood" },
	{ t: "Badhaai Ho", tag: "Bollywood", aka: ["Badhai Ho"] },
	{ t: "Gully Boy", tag: "Bollywood" },
	{ t: "Super 30", tag: "Bollywood", aka: ["Super Thirty"] },
	{ t: "Chhichhore", tag: "Bollywood", aka: ["Chhichore", "Chichore"] },
	{ t: "Mission Mangal", tag: "Bollywood" },
	{ t: "Dream Girl", tag: "Bollywood" },
	{ t: "Bala", tag: "Bollywood" },

	// 2020s
	{ t: "Brahmastra", tag: "Bollywood", aka: ["Brahmastra Part One Shiva"] },
	{ t: "Pathaan", tag: "Bollywood", aka: ["Pathan"] },
	{ t: "83", tag: "Bollywood", aka: ["Eighty Three"] },
	{ t: "Rocky Aur Rani Kii Prem Kahaani", tag: "Bollywood", aka: ["Rocky Aur Rani Ki Prem Kahani", "Rocky Aur Rani"] },
	{ t: "Jawan", tag: "Bollywood" },
	{ t: "12th Fail", tag: "Bollywood", aka: ["Twelfth Fail"] },
	{ t: "Dunki", tag: "Bollywood" },
	{ t: "Laapataa Ladies", tag: "Bollywood", aka: ["Lapata Ladies", "Laapata Ladies"] },
	{ t: "Stree 2", tag: "Bollywood", aka: ["Stree Two"] },
	{ t: "Bhool Bhulaiyaa 2", tag: "Bollywood", aka: ["Bhool Bhulaiya 2", "Bhool Bhulaiyaa Two"] },
	{ t: "Sitaare Zameen Par", tag: "Bollywood", aka: ["Sitare Zameen Par"] },
	{ t: "Saiyaara", tag: "Bollywood", aka: ["Saiyara"] },

	// South
	{ t: "Roja", tag: "South" },
	{ t: "Chandramukhi", tag: "South" },
	{ t: "Sivaji: The Boss", tag: "South", aka: ["Sivaji", "Shivaji The Boss"] },
	{ t: "Enthiran", tag: "South", aka: ["Robot"] },
	{ t: "2.0", tag: "South", aka: ["Robot 2.0", "Robot 2", "Two Point O"] },
	{ t: "Magadheera", tag: "South" },
	{ t: "Eega", tag: "South", aka: ["Makkhi"] },
	{ t: "Baahubali: The Beginning", tag: "South", aka: ["Baahubali", "Bahubali", "Baahubali 1", "Bahubali The Beginning"] },
	{ t: "Baahubali 2: The Conclusion", tag: "South", aka: ["Baahubali 2", "Bahubali 2", "Baahubali Two", "Bahubali 2 The Conclusion"] },
	{ t: "KGF: Chapter 1", tag: "South", aka: ["KGF", "KGF 1", "KGF Chapter One"] },
	{ t: "KGF: Chapter 2", tag: "South", aka: ["KGF 2", "KGF Chapter Two"] },
	{ t: "Ala Vaikunthapurramuloo", tag: "South", aka: ["Ala Vaikunthapuramulo"] },
	{ t: "Pushpa: The Rise", tag: "South", aka: ["Pushpa", "Pushpa 1"] },
	{ t: "Minnal Murali", tag: "South" },
	{ t: "RRR", tag: "South" },
	{ t: "Kantara", tag: "South" },
	{ t: "777 Charlie", tag: "South" },
	{ t: "Ponniyin Selvan", tag: "South", aka: ["PS1", "Ponniyin Selvan 1"] },
	{ t: "HanuMan", tag: "South" },
	{ t: "Kalki 2898 AD", tag: "South", aka: ["Kalki"] },
	{ t: "Sita Ramam", tag: "South", aka: ["Seetha Ramam"] },

	// Hollywood
	{ t: "Titanic", tag: "Hollywood", g: 1 },
	{ t: "Avatar", tag: "Hollywood", g: 1 },
	{ t: "Jurassic Park", tag: "Hollywood", g: 1 },
	{ t: "The Lion King", tag: "Hollywood", g: 1 },
	{ t: "Home Alone", tag: "Hollywood", g: 1 },
	{ t: "Harry Potter", tag: "Hollywood", aka: ["Harry Potter and the Philosopher's Stone", "Harry Potter and the Sorcerer's Stone"], g: 1 },
	{ t: "Avengers: Endgame", tag: "Hollywood", aka: ["Endgame", "Avengers"], g: 1 },
	{ t: "Spider-Man", tag: "Hollywood", g: 1 },
	{ t: "Frozen", tag: "Hollywood", g: 1 },
	{ t: "Jumanji", tag: "Hollywood", g: 1 },
	{ t: "Mission: Impossible", tag: "Hollywood", g: 1 },
	{ t: "The Dark Knight", tag: "Hollywood", g: 1 },
	{ t: "Iron Man", tag: "Hollywood", g: 1 },
	{ t: "Finding Nemo", tag: "Hollywood", g: 1 },
	{ t: "Toy Story", tag: "Hollywood", g: 1 },
	{ t: "Kung Fu Panda", tag: "Hollywood", g: 1 },
	{ t: "Shrek", tag: "Hollywood", g: 1 },
	{ t: "The Jungle Book", tag: "Hollywood", g: 1 },
	{ t: "Pirates of the Caribbean", tag: "Hollywood", aka: ["Pirates of Caribbean", "Pirates of the Carribean"], g: 1 },
	{ t: "Star Wars", tag: "Hollywood", g: 1 },
	{ t: "The Matrix", tag: "Hollywood", g: 1 },
	{ t: "Inception", tag: "Hollywood", g: 1 },
	{ t: "Fast & Furious", tag: "Hollywood", aka: ["Fast and Furious", "The Fast and the Furious"], g: 1 },
	{ t: "Minions", tag: "Hollywood", g: 1 },
	{ t: "Aladdin", tag: "Hollywood", aka: ["Alladin"], g: 1 },
];
