/** Who Am I? people: 90% Indian, 10% famous everywhere. `h` is the hint (category), `aka` other ways people say the name, `g: 1` marks non-Indians. */
export type Person = { n: string; h: string; aka?: string[]; g?: 1 };

export const PEOPLE: Person[] = [
	// Actors
	{ n: "Amitabh Bachchan", h: "Actor", aka: ["Amitabh", "Big B", "Amitabh Bacchan"] },
	{ n: "Shah Rukh Khan", h: "Actor", aka: ["SRK", "Shahrukh", "King Khan"] },
	{ n: "Salman Khan", h: "Actor", aka: ["Salman", "Sallu", "Bhaijaan"] },
	{ n: "Aamir Khan", h: "Actor", aka: ["Aamir", "Amir Khan", "Mr Perfectionist"] },
	{ n: "Akshay Kumar", h: "Actor", aka: ["Akshay", "Akki", "Khiladi Kumar"] },
	{ n: "Hrithik Roshan", h: "Actor", aka: ["Hrithik", "Hritik Roshan"] },
	{ n: "Ranbir Kapoor", h: "Actor", aka: ["Ranbir"] },
	{ n: "Ranveer Singh", h: "Actor", aka: ["Ranveer"] },
	{ n: "Ajay Devgn", h: "Actor", aka: ["Ajay Devgan"] },
	{ n: "Dharmendra", h: "Actor", aka: ["Dharam ji"] },
	{ n: "Sunny Deol", h: "Actor" },
	{ n: "Abhishek Bachchan", h: "Actor", aka: ["Abhishek"] },
	{ n: "Rajesh Khanna", h: "Actor", aka: ["Kaka"] },
	{ n: "Dilip Kumar", h: "Actor" },
	{ n: "Raj Kapoor", h: "Actor" },
	{ n: "Dev Anand", h: "Actor", aka: ["Dev Saab"] },
	{ n: "Jeetendra", h: "Actor", aka: ["Jitendra", "Jumping Jack"] },
	{ n: "Shammi Kapoor", h: "Actor" },
	{ n: "Rishi Kapoor", h: "Actor" },
	{ n: "Anil Kapoor", h: "Actor" },
	{ n: "Govinda", h: "Actor", aka: ["Chi Chi"] },
	{ n: "Mithun Chakraborty", h: "Actor", aka: ["Mithun", "Mithun Da"] },
	{ n: "Jackie Shroff", h: "Actor", aka: ["Jaggu Dada"] },
	{ n: "Suniel Shetty", h: "Actor", aka: ["Sunil Shetty"] },
	{ n: "Amrish Puri", h: "Actor" },
	{ n: "Amjad Khan", h: "Actor" },
	{ n: "Kader Khan", h: "Actor" },
	{ n: "Asrani", h: "Actor" },
	{ n: "Paresh Rawal", h: "Actor" },
	{ n: "Boman Irani", h: "Actor" },
	{ n: "Irrfan Khan", h: "Actor", aka: ["Irrfan", "Irfan Khan"] },
	{ n: "Nawazuddin Siddiqui", h: "Actor", aka: ["Nawazuddin", "Nawaz"] },
	{ n: "Pankaj Tripathi", h: "Actor" },
	{ n: "Manoj Bajpayee", h: "Actor", aka: ["Manoj Bajpai"] },
	{ n: "Rajkummar Rao", h: "Actor", aka: ["Rajkumar Rao"] },
	{ n: "Saif Ali Khan", h: "Actor", aka: ["Saif"] },
	{ n: "John Abraham", h: "Actor" },
	{ n: "Arshad Warsi", h: "Actor", aka: ["Arshad"] },
	{ n: "Shahid Kapoor", h: "Actor", aka: ["Shahid"] },
	{ n: "Sonu Sood", h: "Actor" },
	{ n: "Varun Dhawan", h: "Actor", aka: ["Varun"] },
	{ n: "Tiger Shroff", h: "Actor", aka: ["Tiger"] },
	{ n: "Vicky Kaushal", h: "Actor", aka: ["Vicky"] },
	{ n: "Kartik Aaryan", h: "Actor", aka: ["Kartik", "Kartik Aryan"] },
	{ n: "Ayushmann Khurrana", h: "Actor", aka: ["Ayushmann", "Ayushman Khurana"] },
	{ n: "Rajinikanth", h: "Actor", aka: ["Rajini", "Rajnikanth", "Thalaivar"] },
	{ n: "Kamal Haasan", h: "Actor", aka: ["Kamal", "Kamal Hassan"] },
	{ n: "Chiranjeevi", h: "Actor", aka: ["Chiru"] },
	{ n: "Mohanlal", h: "Actor", aka: ["Lalettan"] },
	{ n: "Mahesh Babu", h: "Actor", aka: ["Mahesh"] },
	{ n: "Prabhas", h: "Actor" },
	{ n: "Allu Arjun", h: "Actor" },
	{ n: "Jr NTR", h: "Actor", aka: ["Junior NTR", "NTR"] },
	{ n: "Ram Charan", h: "Actor" },
	{ n: "Yash", h: "Actor" },
	{ n: "Dhanush", h: "Actor" },

	// Actresses
	{ n: "Madhubala", h: "Actress" },
	{ n: "Nargis", h: "Actress", aka: ["Nargis Dutt"] },
	{ n: "Waheeda Rehman", h: "Actress" },
	{ n: "Rekha", h: "Actress" },
	{ n: "Hema Malini", h: "Actress", aka: ["Dream Girl"] },
	{ n: "Zeenat Aman", h: "Actress", aka: ["Zeenat"] },
	{ n: "Sridevi", h: "Actress" },
	{ n: "Madhuri Dixit", h: "Actress", aka: ["Madhuri"] },
	{ n: "Juhi Chawla", h: "Actress", aka: ["Juhi"] },
	{ n: "Kajol", h: "Actress" },
	{ n: "Aishwarya Rai", h: "Actress", aka: ["Aishwarya", "Ash", "Aishwarya Rai Bachchan"] },
	{ n: "Sushmita Sen", h: "Actress", aka: ["Sushmita"] },
	{ n: "Karisma Kapoor", h: "Actress", aka: ["Karisma", "Karishma Kapoor", "Lolo"] },
	{ n: "Kareena Kapoor", h: "Actress", aka: ["Kareena", "Bebo"] },
	{ n: "Rani Mukerji", h: "Actress", aka: ["Rani Mukherjee"] },
	{ n: "Preity Zinta", h: "Actress", aka: ["Preity", "Preeti Zinta"] },
	{ n: "Shilpa Shetty", h: "Actress", aka: ["Shilpa"] },
	{ n: "Raveena Tandon", h: "Actress", aka: ["Raveena"] },
	{ n: "Tabu", h: "Actress" },
	{ n: "Priyanka Chopra", h: "Actress", aka: ["Priyanka", "PC", "Desi Girl"] },
	{ n: "Deepika Padukone", h: "Actress", aka: ["Deepika"] },
	{ n: "Katrina Kaif", h: "Actress", aka: ["Katrina", "Kat"] },
	{ n: "Vidya Balan", h: "Actress", aka: ["Vidya"] },
	{ n: "Anushka Sharma", h: "Actress", aka: ["Anushka"] },
	{ n: "Sonam Kapoor", h: "Actress", aka: ["Sonam"] },
	{ n: "Alia Bhatt", h: "Actress", aka: ["Alia"] },
	{ n: "Shraddha Kapoor", h: "Actress", aka: ["Shraddha"] },
	{ n: "Kiara Advani", h: "Actress", aka: ["Kiara"] },
	{ n: "Kriti Sanon", h: "Actress", aka: ["Kriti"] },
	{ n: "Taapsee Pannu", h: "Actress", aka: ["Taapsee", "Tapsee Pannu"] },
	{ n: "Janhvi Kapoor", h: "Actress", aka: ["Jhanvi Kapoor"] },
	{ n: "Sara Ali Khan", h: "Actress" },
	{ n: "Samantha Ruth Prabhu", h: "Actress", aka: ["Samantha"] },
	{ n: "Rashmika Mandanna", h: "Actress", aka: ["Rashmika"] },
	{ n: "Nayanthara", h: "Actress" },
	{ n: "Tamannaah Bhatia", h: "Actress", aka: ["Tamannaah", "Tamanna", "Tamanna Bhatia"] },

	// Film directors
	{ n: "Satyajit Ray", h: "Film director" },
	{ n: "Karan Johar", h: "Film director", aka: ["KJo"] },
	{ n: "SS Rajamouli", h: "Film director", aka: ["Rajamouli"] },
	{ n: "Sanjay Leela Bhansali", h: "Film director", aka: ["Bhansali", "SLB"] },
	{ n: "Rohit Shetty", h: "Film director" },
	{ n: "Farah Khan", h: "Film director" },
	{ n: "Yash Chopra", h: "Film director" },
	{ n: "Rajkumar Hirani", h: "Film director", aka: ["Raju Hirani", "Hirani"] },
	{ n: "Mani Ratnam", h: "Film director" },

	// Cricketers
	{ n: "Sachin Tendulkar", h: "Cricketer", aka: ["Sachin", "Master Blaster", "God of Cricket"] },
	{ n: "MS Dhoni", h: "Cricketer", aka: ["Dhoni", "MSD", "Mahi", "Thala", "Mahendra Singh Dhoni", "Captain Cool"] },
	{ n: "Virat Kohli", h: "Cricketer", aka: ["Virat", "Kohli", "King Kohli"] },
	{ n: "Rohit Sharma", h: "Cricketer", aka: ["Hitman"] },
	{ n: "Kapil Dev", h: "Cricketer" },
	{ n: "Sunil Gavaskar", h: "Cricketer", aka: ["Gavaskar", "Sunny Gavaskar", "Little Master"] },
	{ n: "Rahul Dravid", h: "Cricketer", aka: ["Dravid", "The Wall"] },
	{ n: "Sourav Ganguly", h: "Cricketer", aka: ["Ganguly", "Dada", "Saurav Ganguly"] },
	{ n: "Yuvraj Singh", h: "Cricketer", aka: ["Yuvraj", "Yuvi"] },
	{ n: "Virender Sehwag", h: "Cricketer", aka: ["Sehwag", "Viru"] },
	{ n: "Anil Kumble", h: "Cricketer", aka: ["Kumble"] },
	{ n: "VVS Laxman", h: "Cricketer", aka: ["Laxman"] },
	{ n: "Harbhajan Singh", h: "Cricketer", aka: ["Harbhajan", "Bhajji"] },
	{ n: "Zaheer Khan", h: "Cricketer", aka: ["Zaheer", "Zak"] },
	{ n: "Gautam Gambhir", h: "Cricketer", aka: ["Gambhir", "Gauti"] },
	{ n: "Suresh Raina", h: "Cricketer", aka: ["Raina"] },
	{ n: "Ravi Shastri", h: "Cricketer" },
	{ n: "Shikhar Dhawan", h: "Cricketer", aka: ["Dhawan", "Gabbar"] },
	{ n: "Jasprit Bumrah", h: "Cricketer", aka: ["Bumrah"] },
	{ n: "Ravindra Jadeja", h: "Cricketer", aka: ["Jadeja", "Jaddu", "Sir Jadeja"] },
	{ n: "Ravichandran Ashwin", h: "Cricketer", aka: ["Ashwin", "R Ashwin"] },
	{ n: "Hardik Pandya", h: "Cricketer", aka: ["Hardik", "Pandya"] },
	{ n: "Shubman Gill", h: "Cricketer", aka: ["Shubman", "Gill"] },
	{ n: "KL Rahul", h: "Cricketer" },
	{ n: "Rishabh Pant", h: "Cricketer", aka: ["Pant", "Rishabh"] },
	{ n: "Suryakumar Yadav", h: "Cricketer", aka: ["SKY", "Surya"] },
	{ n: "Mohammed Shami", h: "Cricketer", aka: ["Shami"] },
	{ n: "Mohammed Siraj", h: "Cricketer", aka: ["Siraj"] },
	{ n: "Mithali Raj", h: "Cricketer", aka: ["Mithali"] },
	{ n: "Smriti Mandhana", h: "Cricketer", aka: ["Smriti"] },
	{ n: "Harmanpreet Kaur", h: "Cricketer", aka: ["Harmanpreet", "Harman"] },

	// Athletes
	{ n: "Neeraj Chopra", h: "Athlete", aka: ["Neeraj"] },
	{ n: "Milkha Singh", h: "Athlete", aka: ["Flying Sikh"] },
	{ n: "PT Usha", h: "Athlete", aka: ["Payyoli Express"] },
	{ n: "Hima Das", h: "Athlete" },
	{ n: "Dhyan Chand", h: "Hockey player", aka: ["Major Dhyan Chand"] },
	{ n: "PV Sindhu", h: "Badminton player", aka: ["Sindhu"] },
	{ n: "Saina Nehwal", h: "Badminton player", aka: ["Saina"] },
	{ n: "Mary Kom", h: "Boxer", aka: ["MC Mary Kom"] },
	{ n: "Sania Mirza", h: "Tennis player", aka: ["Sania"] },
	{ n: "Leander Paes", h: "Tennis player", aka: ["Leander"] },
	{ n: "Sunil Chhetri", h: "Footballer", aka: ["Chhetri", "Sunil Chetri"] },
	{ n: "Bhaichung Bhutia", h: "Footballer", aka: ["Baichung Bhutia"] },
	{ n: "Viswanathan Anand", h: "Chess player", aka: ["Vishy Anand", "Vishwanathan Anand"] },
	{ n: "Gukesh", h: "Chess player", aka: ["D Gukesh", "Gukesh D"] },
	{ n: "Abhinav Bindra", h: "Shooter", aka: ["Bindra"] },
	{ n: "Manu Bhaker", h: "Shooter", aka: ["Manu Bhakar"] },
	{ n: "Mirabai Chanu", h: "Weightlifter", aka: ["Mirabai", "Meerabai Chanu"] },
	{ n: "Dara Singh", h: "Wrestler" },
	{ n: "The Great Khali", h: "Wrestler", aka: ["Khali", "Great Khali"] },
	{ n: "Geeta Phogat", h: "Wrestler", aka: ["Gita Phogat"] },

	// Singers and composers
	{ n: "Lata Mangeshkar", h: "Singer", aka: ["Lata", "Lata ji", "Lata Didi"] },
	{ n: "Asha Bhosle", h: "Singer", aka: ["Asha", "Asha ji"] },
	{ n: "Kishore Kumar", h: "Singer", aka: ["Kishore", "Kishore Da"] },
	{ n: "Mohammed Rafi", h: "Singer", aka: ["Rafi", "Mohammad Rafi", "Rafi Sahab"] },
	{ n: "Mukesh", h: "Singer" },
	{ n: "Kumar Sanu", h: "Singer" },
	{ n: "Udit Narayan", h: "Singer" },
	{ n: "Alka Yagnik", h: "Singer" },
	{ n: "SP Balasubrahmanyam", h: "Singer", aka: ["SPB", "SP Balasubramaniam"] },
	{ n: "Jagjit Singh", h: "Singer", aka: ["Jagjit"] },
	{ n: "Sonu Nigam", h: "Singer" },
	{ n: "Shaan", h: "Singer" },
	{ n: "KK", h: "Singer" },
	{ n: "Shreya Ghoshal", h: "Singer", aka: ["Shreya"] },
	{ n: "Sunidhi Chauhan", h: "Singer", aka: ["Sunidhi"] },
	{ n: "Kailash Kher", h: "Singer" },
	{ n: "Shankar Mahadevan", h: "Singer" },
	{ n: "Mika Singh", h: "Singer", aka: ["Mika"] },
	{ n: "Arijit Singh", h: "Singer", aka: ["Arijit"] },
	{ n: "Jubin Nautiyal", h: "Singer", aka: ["Jubin"] },
	{ n: "Neha Kakkar", h: "Singer", aka: ["Neha"] },
	{ n: "Himesh Reshammiya", h: "Singer", aka: ["Himesh"] },
	{ n: "Diljit Dosanjh", h: "Singer", aka: ["Diljit"] },
	{ n: "Guru Randhawa", h: "Singer" },
	{ n: "Yo Yo Honey Singh", h: "Rapper", aka: ["Honey Singh"] },
	{ n: "Badshah", h: "Rapper", aka: ["Baadshah"] },
	{ n: "AR Rahman", h: "Music composer", aka: ["Rahman", "ARR"] },
	{ n: "RD Burman", h: "Music composer", aka: ["Pancham", "Pancham Da"] },
	{ n: "Ilaiyaraaja", h: "Music composer", aka: ["Ilayaraja", "Ilaiyaraja"] },
	{ n: "Bappi Lahiri", h: "Music composer", aka: ["Bappi Da", "Bappi Lahri"] },
	{ n: "Pritam", h: "Music composer" },
	{ n: "Zakir Hussain", h: "Tabla player", aka: ["Ustad Zakir Hussain"] },
	{ n: "Gulzar", h: "Lyricist", aka: ["Gulzar Sahab"] },

	// Freedom fighters
	{ n: "Mahatma Gandhi", h: "Freedom fighter", aka: ["Gandhiji", "Bapu", "MK Gandhi", "Mohandas Karamchand Gandhi"] },
	{ n: "Bhagat Singh", h: "Freedom fighter", aka: ["Shaheed Bhagat Singh"] },
	{ n: "Rajguru", h: "Freedom fighter" },
	{ n: "Sukhdev", h: "Freedom fighter" },
	{ n: "Subhas Chandra Bose", h: "Freedom fighter", aka: ["Netaji", "Subhash Chandra Bose"] },
	{ n: "Chandrashekhar Azad", h: "Freedom fighter", aka: ["Azad"] },
	{ n: "Sardar Patel", h: "Freedom fighter", aka: ["Vallabhbhai Patel", "Sardar Vallabhbhai Patel"] },
	{ n: "Bal Gangadhar Tilak", h: "Freedom fighter", aka: ["Tilak", "Lokmanya Tilak"] },
	{ n: "Lala Lajpat Rai", h: "Freedom fighter", aka: ["Lajpat Rai"] },
	{ n: "Mangal Pandey", h: "Freedom fighter" },
	{ n: "Tatya Tope", h: "Freedom fighter", aka: ["Tantia Tope"] },
	{ n: "Udham Singh", h: "Freedom fighter", aka: ["Sardar Udham Singh"] },
	{ n: "Sarojini Naidu", h: "Freedom fighter", aka: ["Nightingale of India"] },
	{ n: "Birsa Munda", h: "Freedom fighter" },

	// Kings, emperors and historical figures
	{ n: "Rani Lakshmibai", h: "Queen", aka: ["Lakshmibai", "Rani Laxmibai", "Jhansi ki Rani", "Rani of Jhansi"] },
	{ n: "Shivaji Maharaj", h: "King", aka: ["Shivaji", "Chhatrapati Shivaji", "Chhatrapati Shivaji Maharaj"] },
	{ n: "Maharana Pratap", h: "King", aka: ["Rana Pratap"] },
	{ n: "Prithviraj Chauhan", h: "King", aka: ["Prithviraj"] },
	{ n: "Ashoka", h: "Emperor", aka: ["Ashok", "Ashoka the Great", "Samrat Ashok"] },
	{ n: "Chandragupta Maurya", h: "Emperor", aka: ["Chandragupta"] },
	{ n: "Akbar", h: "Emperor", aka: ["Akbar the Great"] },
	{ n: "Shah Jahan", h: "Emperor" },
	{ n: "Mumtaz Mahal", h: "Empress" },
	{ n: "Birbal", h: "Courtier", aka: ["Raja Birbal"] },
	{ n: "Tansen", h: "Musician", aka: ["Mian Tansen"] },
	{ n: "Chanakya", h: "Philosopher", aka: ["Kautilya"] },
	{ n: "Sam Manekshaw", h: "Army officer", aka: ["Sam Bahadur", "Field Marshal Manekshaw"] },
	{ n: "Vikram Batra", h: "Army officer", aka: ["Captain Vikram Batra", "Sher Shah"] },

	// Saints, reformers and writers
	{ n: "Swami Vivekananda", h: "Monk", aka: ["Vivekananda"] },
	{ n: "Mother Teresa", h: "Nun", aka: ["Saint Teresa"] },
	{ n: "BR Ambedkar", h: "Social reformer", aka: ["Ambedkar", "Babasaheb Ambedkar", "Bhimrao Ambedkar", "Dr Ambedkar"] },
	{ n: "Raja Ram Mohan Roy", h: "Social reformer", aka: ["Ram Mohan Roy"] },
	{ n: "Savitribai Phule", h: "Social reformer" },
	{ n: "Kabir", h: "Poet saint", aka: ["Sant Kabir", "Kabir Das"] },
	{ n: "Tulsidas", h: "Poet saint", aka: ["Goswami Tulsidas"] },
	{ n: "Rabindranath Tagore", h: "Poet", aka: ["Tagore", "Gurudev"] },
	{ n: "Mirza Ghalib", h: "Poet", aka: ["Ghalib"] },
	{ n: "Kalidas", h: "Poet", aka: ["Kalidasa"] },
	{ n: "Harivansh Rai Bachchan", h: "Poet" },
	{ n: "Munshi Premchand", h: "Writer", aka: ["Premchand"] },
	{ n: "RK Narayan", h: "Author" },
	{ n: "Ruskin Bond", h: "Author" },
	{ n: "Chetan Bhagat", h: "Author" },
	{ n: "Sudha Murty", h: "Author" },

	// Prime Ministers
	{ n: "Jawaharlal Nehru", h: "Prime Minister", aka: ["Nehru", "Chacha Nehru", "Pandit Nehru"] },
	{ n: "Lal Bahadur Shastri", h: "Prime Minister", aka: ["Lal Bahadur", "Shastri ji"] },
	{ n: "Indira Gandhi", h: "Prime Minister", aka: ["Indira"] },
	{ n: "Rajiv Gandhi", h: "Prime Minister", aka: ["Rajiv"] },
	{ n: "PV Narasimha Rao", h: "Prime Minister", aka: ["Narasimha Rao"] },
	{ n: "Atal Bihari Vajpayee", h: "Prime Minister", aka: ["Vajpayee", "Atal ji", "Atal Bihari"] },
	{ n: "Manmohan Singh", h: "Prime Minister", aka: ["Manmohan", "Dr Manmohan Singh"] },

	// Presidents
	{ n: "Rajendra Prasad", h: "President", aka: ["Dr Rajendra Prasad"] },
	{ n: "Sarvepalli Radhakrishnan", h: "President", aka: ["Radhakrishnan", "S Radhakrishnan", "Dr Radhakrishnan"] },
	{ n: "Pratibha Patil", h: "President" },
	{ n: "Pranab Mukherjee", h: "President", aka: ["Pranab Da"] },
	{ n: "Ram Nath Kovind", h: "President" },

	// Scientists
	{ n: "APJ Abdul Kalam", h: "Scientist", aka: ["Abdul Kalam", "Kalam", "Dr Kalam", "Missile Man"] },
	{ n: "CV Raman", h: "Physicist", aka: ["Sir CV Raman", "Raman"] },
	{ n: "Homi Bhabha", h: "Physicist", aka: ["Homi J Bhabha", "Bhabha"] },
	{ n: "Vikram Sarabhai", h: "Scientist" },
	{ n: "Jagadish Chandra Bose", h: "Scientist", aka: ["JC Bose"] },
	{ n: "Srinivasa Ramanujan", h: "Mathematician", aka: ["Ramanujan"] },
	{ n: "Aryabhata", h: "Mathematician", aka: ["Aryabhatta"] },
	{ n: "Shakuntala Devi", h: "Mathematician", aka: ["Human Computer"] },
	{ n: "Kalpana Chawla", h: "Astronaut", aka: ["Kalpana"] },
	{ n: "Rakesh Sharma", h: "Astronaut" },

	// Business
	{ n: "Ratan Tata", h: "Industrialist" },
	{ n: "JRD Tata", h: "Industrialist" },
	{ n: "Dhirubhai Ambani", h: "Businessman", aka: ["Dhirubhai"] },
	{ n: "Mukesh Ambani", h: "Businessman" },
	{ n: "Nita Ambani", h: "Businesswoman" },
	{ n: "Azim Premji", h: "Businessman" },
	{ n: "Anand Mahindra", h: "Businessman" },
	{ n: "Narayana Murthy", h: "Tech founder", aka: ["NR Narayana Murthy"] },
	{ n: "Sundar Pichai", h: "Tech CEO", aka: ["Sundar"] },
	{ n: "Satya Nadella", h: "Tech CEO", aka: ["Nadella"] },

	// Comedians, creators and TV
	{ n: "Johnny Lever", h: "Comedian" },
	{ n: "Raju Srivastava", h: "Comedian" },
	{ n: "Kapil Sharma", h: "Comedian" },
	{ n: "Sunil Grover", h: "Comedian" },
	{ n: "Bharti Singh", h: "Comedian", aka: ["Bharti"] },
	{ n: "Zakir Khan", h: "Comedian" },
	{ n: "Ekta Kapoor", h: "TV producer" },
	{ n: "Bhuvan Bam", h: "YouTuber", aka: ["Bhuvan", "BB Ki Vines"] },
	{ n: "Sanjeev Kapoor", h: "Chef" },
	{ n: "Prabhu Deva", h: "Dancer" },

	// Famous everywhere
	{ n: "Albert Einstein", h: "Physicist", aka: ["Einstein"], g: 1 },
	{ n: "Isaac Newton", h: "Scientist", aka: ["Newton", "Sir Isaac Newton"], g: 1 },
	{ n: "Stephen Hawking", h: "Physicist", aka: ["Hawking"], g: 1 },
	{ n: "Thomas Edison", h: "Inventor", aka: ["Edison"], g: 1 },
	{ n: "Alexander Graham Bell", h: "Inventor", aka: ["Graham Bell"], g: 1 },
	{ n: "Neil Armstrong", h: "Astronaut", aka: ["Armstrong"], g: 1 },
	{ n: "Leonardo da Vinci", h: "Painter", aka: ["Da Vinci"], g: 1 },
	{ n: "William Shakespeare", h: "Playwright", aka: ["Shakespeare"], g: 1 },
	{ n: "Queen Elizabeth II", h: "Queen", aka: ["Queen Elizabeth", "Elizabeth II"], g: 1 },
	{ n: "Abraham Lincoln", h: "President", aka: ["Lincoln"], g: 1 },
	{ n: "Nelson Mandela", h: "President", aka: ["Mandela"], g: 1 },
	{ n: "Barack Obama", h: "President", aka: ["Obama"], g: 1 },
	{ n: "Steve Jobs", h: "Tech founder", g: 1 },
	{ n: "Bill Gates", h: "Tech founder", aka: ["Gates"], g: 1 },
	{ n: "Mark Zuckerberg", h: "Tech founder", aka: ["Zuckerberg", "Zuck"], g: 1 },
	{ n: "Walt Disney", h: "Animator", aka: ["Disney"], g: 1 },
	{ n: "Charlie Chaplin", h: "Comedian", aka: ["Chaplin"], g: 1 },
	{ n: "Rowan Atkinson", h: "Comedian", aka: ["Mr Bean"], g: 1 },
	{ n: "Jackie Chan", h: "Actor", g: 1 },
	{ n: "Bruce Lee", h: "Martial artist", g: 1 },
	{ n: "Tom Cruise", h: "Actor", g: 1 },
	{ n: "Leonardo DiCaprio", h: "Actor", aka: ["DiCaprio", "Leo DiCaprio"], g: 1 },
	{ n: "Dwayne Johnson", h: "Actor", aka: ["The Rock"], g: 1 },
	{ n: "Michael Jackson", h: "Pop star", aka: ["MJ", "King of Pop"], g: 1 },
	{ n: "Taylor Swift", h: "Pop star", aka: ["Taylor"], g: 1 },
	{ n: "Shakira", h: "Singer", g: 1 },
	{ n: "Lionel Messi", h: "Footballer", aka: ["Messi", "Leo Messi"], g: 1 },
	{ n: "Cristiano Ronaldo", h: "Footballer", aka: ["Ronaldo", "CR7"], g: 1 },
	{ n: "Usain Bolt", h: "Athlete", aka: ["Bolt"], g: 1 },
	{ n: "Roger Federer", h: "Tennis player", aka: ["Federer"], g: 1 },
];
