/** Songs for Emoji Movie: 90% Indian, 10% famous everywhere. `from` is the film (or the artist for non-film songs). `g: 1` marks non-Indian. */
export type Song = { t: string; from: string; aka?: string[]; g?: 1 };

export const SONGS: Song[] = [
	// Classics
	{ t: "Mera Joota Hai Japani", from: "Shree 420", aka: ["Mera Juta Hai Japani"] },
	{ t: "Awara Hoon", from: "Awaara", aka: ["Awaara Hoon"] },
	{ t: "Chanda Mama Door Ke", from: "Vachan" },
	{ t: "Eena Meena Deeka", from: "Aasha" },
	{ t: "Sar Jo Tera Chakraye", from: "Pyaasa", aka: ["Sar Jo Tera Chakraaye"] },
	{ t: "Yeh Desh Hai Veer Jawanon Ka", from: "Naya Daur", aka: ["Ye Desh Hai Veer Jawanon Ka"] },
	{ t: "Paanch Rupaiya Barah Aana", from: "Chalti Ka Naam Gaadi", aka: ["Paanch Rupaiya Baara Aana"] },
	{ t: "Nani Teri Morni", from: "Masoom (1960)", aka: ["Nani Teri Morni Ko Mor Le Gaye"] },
	{ t: "Chahe Koi Mujhe Junglee Kahe", from: "Junglee", aka: ["Yahoo", "Yahoo Chahe Koi Mujhe Junglee Kahe"] },
	{ t: "Govinda Aala Re", from: "Bluff Master", aka: ["Govinda Ala Re"] },
	{ t: "Lag Ja Gale", from: "Woh Kaun Thi?" },
	{ t: "Aaj Phir Jeene Ki Tamanna Hai", from: "Guide" },
	{ t: "Jhumka Gira Re", from: "Mera Saaya", aka: ["Jhumka Gira Re Bareilly Ke Bazaar Mein"] },
	{ t: "Baar Baar Din Yeh Aaye", from: "Farz", aka: ["Baar Baar Din Ye Aaye", "Bar Bar Din Yeh Aaye"] },
	{ t: "Ek Chatur Naar", from: "Padosan" },
	{ t: "Mere Sapno Ki Rani", from: "Aradhana" },
	{ t: "Jeena Yahan Marna Yahan", from: "Mera Naam Joker" },
	{ t: "Chal Chal Chal Mere Haathi", from: "Haathi Mere Saathi", aka: ["Chal Chal Chal Mere Hathi"] },
	{ t: "Zindagi Ek Safar Hai Suhana", from: "Andaz (1971)" },
	{ t: "Jai Jai Shiv Shankar", from: "Aap Ki Kasam" },
	{ t: "Yeh Dosti", from: "Sholay", aka: ["Yeh Dosti Hum Nahin Todenge", "Ye Dosti"] },
	{ t: "Holi Ke Din", from: "Sholay", aka: ["Holi Ke Din Dil Khil Jaate Hain"] },
	{ t: "My Name Is Anthony Gonsalves", from: "Amar Akbar Anthony", aka: ["Anthony Gonsalves"] },
	{ t: "Bachna Ae Haseeno", from: "Hum Kisise Kum Naheen", aka: ["Bachna Aye Haseeno"] },
	{ t: "Aaj Mere Yaar Ki Shaadi Hai", from: "Aadmi Sadak Ka", aka: ["Mere Yaar Ki Shaadi Hai"] },
	{ t: "Khaike Paan Banaraswala", from: "Don (1978)", aka: ["Khaike Paan"] },
	{ t: "Aane Wala Pal", from: "Golmaal (1979)", aka: ["Aane Wala Pal Jaane Wala Hai"] },
	{ t: "Rang Barse", from: "Silsila", aka: ["Rang Barse Bheege Chunar Wali"] },
	{ t: "Tere Jaisa Yaar Kahan", from: "Yaarana", aka: ["Tere Jaisa Yaar Kaha"] },
	{ t: "Mere Angne Mein", from: "Laawaris", aka: ["Mere Angane Mein"] },
	{ t: "I Am a Disco Dancer", from: "Disco Dancer", aka: ["Im a Disco Dancer"] },
	{ t: "Jimmy Jimmy Aaja Aaja", from: "Disco Dancer", aka: ["Jimmy Jimmy Jimmy Aaja", "Jimmy Jimmy"] },
	{ t: "Lakdi Ki Kathi", from: "Masoom (1983)", aka: ["Lakdi Ki Kaathi"] },
	{ t: "Hawa Hawai", from: "Mr. India", aka: ["Hawa Hawaii"] },
	{ t: "Papa Kehte Hain", from: "Qayamat Se Qayamat Tak", aka: ["Papa Kehte Hain Bada Naam Karega"] },
	{ t: "Kabootar Ja Ja Ja", from: "Maine Pyar Kiya", aka: ["Kabutar Ja Ja Ja"] },
	{ t: "Mere Haathon Mein Nau Nau Chudiyan", from: "Chandni", aka: ["Mere Hathon Mein Nau Nau Chudiyan", "Nau Nau Chudiyan"] },

	// 90s
	{ t: "Dil Hai Chhota Sa", from: "Roja", aka: ["Dil Hai Chota Sa"] },
	{ t: "Pehla Nasha", from: "Jo Jeeta Wohi Sikandar" },
	{ t: "Didi Tera Devar Deewana", from: "Hum Aapke Hain Koun", aka: ["Didi Tera Dewar Deewana"] },
	{ t: "Joote Do Paise Lo", from: "Hum Aapke Hain Koun", aka: ["Jute Do Paise Lo"] },
	{ t: "Mukkala Mukkabla", from: "Kaadhalan", aka: ["Muqabla", "Muqabla Muqabla", "Mukkala Muqabla"] },
	{ t: "Urvasi Urvasi", from: "Kaadhalan", aka: ["Urvashi Urvashi", "Urvashi"] },
	{ t: "Ole Ole", from: "Yeh Dillagi" },
	{ t: "Mehndi Laga Ke Rakhna", from: "Dilwale Dulhania Le Jayenge" },
	{ t: "Tujhe Dekha To", from: "Dilwale Dulhania Le Jayenge", aka: ["Tujhe Dekha To Yeh Jaana Sanam"] },
	{ t: "Made in India", from: "Alisha Chinai" },
	{ t: "Bolo Ta Ra Ra", from: "Daler Mehndi" },
	{ t: "Rangeela Re", from: "Rangeela" },
	{ t: "Tunak Tunak Tun", from: "Daler Mehndi" },
	{ t: "Maa Tujhe Salaam", from: "A. R. Rahman", aka: ["Vande Mataram"] },
	{ t: "Koi Ladki Hai", from: "Dil To Pagal Hai" },
	{ t: "I Love My India", from: "Pardes" },
	{ t: "Chaiyya Chaiyya", from: "Dil Se", aka: ["Chal Chaiyya Chaiyya", "Chaiya Chaiya"] },
	{ t: "Saajanji Ghar Aaye", from: "Kuch Kuch Hota Hai", aka: ["Sajanji Ghar Aaye"] },
	{ t: "Ladki Badi Anjani Hai", from: "Kuch Kuch Hota Hai" },
	{ t: "Mundian To Bach Ke", from: "Panjabi MC", aka: ["Mundian To Bach Ke Rahi"] },
	{ t: "Chunari Chunari", from: "Biwi No. 1", aka: ["Chunri Chunri"] },
	{ t: "Dholi Taro Dhol Baaje", from: "Hum Dil De Chuke Sanam", aka: ["Dhol Baaje", "Dholi Taro"] },
	{ t: "Taal Se Taal Mila", from: "Taal" },
	{ t: "Yaaron", from: "KK", aka: ["Yaaron Dosti Badi Hi Haseen Hai", "Yaaron Dosti"] },

	// 2000s
	{ t: "Aankhen Khuli", from: "Mohabbatein", aka: ["Aankhen Khuli Ho Ya Ho Band"] },
	{ t: "Ek Pal Ka Jeena", from: "Kaho Naa... Pyaar Hai" },
	{ t: "Main Nikla Gaddi Leke", from: "Gadar: Ek Prem Katha", aka: ["Main Nikla Gaddi Lekar", "Main Nikla Gadi Leke"] },
	{ t: "Koi Kahe Kehta Rahe", from: "Dil Chahta Hai" },
	{ t: "Bole Chudiyan", from: "Kabhi Khushi Kabhie Gham", aka: ["Bole Chudiyaan"] },
	{ t: "Say Shava Shava", from: "Kabhi Khushi Kabhie Gham", aka: ["Shava Shava"] },
	{ t: "It's the Time to Disco", from: "Kal Ho Naa Ho", aka: ["Time to Disco"] },
	{ t: "Pretty Woman", from: "Kal Ho Naa Ho" },
	{ t: "Dhoom Machale", from: "Dhoom", aka: ["Dhoom Machale Dhoom"] },
	{ t: "Suno Gaur Se Duniya Walo", from: "Dus", aka: ["Suno Gaur Se Duniya Waalo"] },
	{ t: "Dus Bahane", from: "Dus", aka: ["Dus Bahane Karke"] },
	{ t: "Masti Ki Paathshaala", from: "Rang De Basanti", aka: ["Masti Ki Pathshala"] },
	{ t: "Morya Re", from: "Don (2006)", aka: ["Mourya Re"] },
	{ t: "Bum Bum Bole", from: "Taare Zameen Par" },
	{ t: "Dard-e-Disco", from: "Om Shanti Om" },
	{ t: "Deewangi Deewangi", from: "Om Shanti Om", aka: ["Deewanagi Deewanagi"] },
	{ t: "Mauja Hi Mauja", from: "Jab We Met" },
	{ t: "Nagada Nagada", from: "Jab We Met", aka: ["Nagada Nagada Baja"] },
	{ t: "Khwaja Mere Khwaja", from: "Jodhaa Akbar" },
	{ t: "Pappu Can't Dance", from: "Jaane Tu... Ya Jaane Na" },
	{ t: "Kabhi Kabhi Aditi", from: "Jaane Tu... Ya Jaane Na" },
	{ t: "Desi Girl", from: "Dostana" },
	{ t: "Dance Pe Chance", from: "Rab Ne Bana Di Jodi" },
	{ t: "Jai Ho", from: "Slumdog Millionaire" },
	{ t: "Masakali", from: "Delhi-6", aka: ["Masakalli"] },
	{ t: "Sasural Genda Phool", from: "Delhi-6", aka: ["Genda Phool"] },
	{ t: "Aal Izz Well", from: "3 Idiots", aka: ["All Is Well", "All Izz Well"] },
	{ t: "Give Me Some Sunshine", from: "3 Idiots" },

	// 2010s
	{ t: "Ainvayi Ainvayi", from: "Band Baaja Baaraat", aka: ["Ainvayi"] },
	{ t: "Sadi Gali", from: "Tanu Weds Manu", aka: ["Saadi Gali"] },
	{ t: "Dhinka Chika", from: "Ready" },
	{ t: "Senorita", from: "Zindagi Na Milegi Dobara" },
	{ t: "Kun Faya Kun", from: "Rockstar", aka: ["Kun Faaya Kun"] },
	{ t: "Sadda Haq", from: "Rockstar" },
	{ t: "Why This Kolaveri Di", from: "3 (2012)", aka: ["Kolaveri Di", "Kolaveri"] },
	{ t: "Deva Shree Ganesha", from: "Agneepath (2012)", aka: ["Deva Shri Ganesha"] },
	{ t: "Go Go Govinda", from: "OMG: Oh My God!" },
	{ t: "Badtameez Dil", from: "Yeh Jawaani Hai Deewani" },
	{ t: "Balam Pichkari", from: "Yeh Jawaani Hai Deewani" },
	{ t: "Dilli Wali Girlfriend", from: "Yeh Jawaani Hai Deewani", aka: ["Dilliwaali Girlfriend"] },
	{ t: "Lungi Dance", from: "Chennai Express" },
	{ t: "1234 Get On The Dance Floor", from: "Chennai Express", aka: ["One Two Three Four", "Get On The Dance Floor"] },
	{ t: "Blue Eyes", from: "Yo Yo Honey Singh" },
	{ t: "Tune Maari Entriyaan", from: "Gunday", aka: ["Tune Mari Entriyan"] },
	{ t: "Nagada Sang Dhol", from: "Goliyon Ki Raasleela Ram-Leela", aka: ["Nagada Sang Dhol Baaje"] },
	{ t: "London Thumakda", from: "Queen" },
	{ t: "Sooraj Dooba Hai", from: "Roy", aka: ["Suraj Dooba Hai"] },
	{ t: "Abhi Toh Party Shuru Hui Hai", from: "Khoobsurat (2014)", aka: ["Abhi To Party Shuru Hui Hai"] },
	{ t: "Saturday Saturday", from: "Humpty Sharma Ki Dulhania" },
	{ t: "Selfie Le Le Re", from: "Bajrangi Bhaijaan" },
	{ t: "Gallan Goodiyaan", from: "Dil Dhadakne Do", aka: ["Gallan Gudiyan", "Gallan Goodiyan"] },
	{ t: "Malhari", from: "Bajirao Mastani" },
	{ t: "Kar Gayi Chull", from: "Kapoor & Sons", aka: ["Chull"] },
	{ t: "Kala Chashma", from: "Baar Baar Dekho", aka: ["Kaala Chashma"] },
	{ t: "Zingaat", from: "Sairat", aka: ["Jhingaat"] },
	{ t: "Haanikaarak Bapu", from: "Dangal", aka: ["Hanikarak Bapu"] },
	{ t: "Badri Ki Dulhania", from: "Badrinath Ki Dulhania" },
	{ t: "Tamma Tamma Again", from: "Badrinath Ki Dulhania", aka: ["Tamma Tamma"] },
	{ t: "Sweety Tera Drama", from: "Bareilly Ki Barfi" },
	{ t: "Jimikki Kammal", from: "Velipadinte Pusthakam", aka: ["Jimiki Kammal"] },
	{ t: "Swag Se Swagat", from: "Tiger Zinda Hai" },
	{ t: "Ghoomar", from: "Padmaavat" },
	{ t: "Bom Diggy Diggy", from: "Sonu Ke Titu Ki Sweety", aka: ["Bom Diggy"] },
	{ t: "Rowdy Baby", from: "Maari 2" },
	{ t: "Apna Time Aayega", from: "Gully Boy" },
	{ t: "Teri Mitti", from: "Kesari" },

	// 2020s
	{ t: "Butta Bomma", from: "Ala Vaikunthapurramuloo" },
	{ t: "Vaathi Coming", from: "Master" },
	{ t: "Srivalli", from: "Pushpa: The Rise", aka: ["Shrivalli"] },
	{ t: "Naatu Naatu", from: "RRR", aka: ["Nacho Nacho", "Natu Natu"] },
	{ t: "Kesariya", from: "Brahmastra", aka: ["Kesariya Tera Ishq Hai Piya"] },
	{ t: "Jhoome Jo Pathaan", from: "Pathaan", aka: ["Jhoome Jo Pathan"] },
	{ t: "What Jhumka?", from: "Rocky Aur Rani Kii Prem Kahaani" },
	{ t: "Zinda Banda", from: "Jawan" },

	// Global
	{ t: "Thriller", from: "Michael Jackson", g: 1 },
	{ t: "We Will Rock You", from: "Queen", g: 1 },
	{ t: "Macarena", from: "Los del Rio", g: 1 },
	{ t: "Hakuna Matata", from: "The Lion King", g: 1 },
	{ t: "Baby", from: "Justin Bieber", g: 1 },
	{ t: "Waka Waka", from: "Shakira", aka: ["Waka Waka This Time for Africa", "This Time for Africa"], g: 1 },
	{ t: "Gangnam Style", from: "PSY", g: 1 },
	{ t: "Let It Go", from: "Frozen", g: 1 },
	{ t: "Hello", from: "Adele", g: 1 },
	{ t: "See You Again", from: "Furious 7", g: 1 },
	{ t: "Baby Shark", from: "Pinkfong", g: 1 },
	{ t: "Despacito", from: "Luis Fonsi ft. Daddy Yankee", g: 1 },
	{ t: "Believer", from: "Imagine Dragons", g: 1 },
	{ t: "Dance Monkey", from: "Tones and I", g: 1 },
	{ t: "Blinding Lights", from: "The Weeknd", g: 1 },
];
