/** Same Wave scales: [left end, right end]. */
export type Wave = [left: string, right: string];

export const WAVES: Wave[] = [
	["Mild", "Spicy"],
	["Messy", "Neat"],
	["Dark", "Bright"],
	["Flop movie", "Blockbuster"],
	["Street food", "Fancy restaurant food"],
	["Easy to cook", "Hard to cook"],
	["Villain", "Hero"],
	["Underrated", "Overrated"],
	["Cheap", "Expensive"],
	["Useless superpower", "Amazing superpower"],
	["Harmless", "Dangerous"],
	["Guilty pleasure", "Proud of it"],
	["Sad song", "Happy song"],
	["Morning thing", "Midnight thing"],
	["Delhi winter", "Delhi summer"],
	["Healthy", "Unhealthy"],
	["Snooze fest", "Last-over thriller"],
	["Mithai", "Namkeen"],
	["Doordarshan era", "Instagram era"],
	["For kids", "For grown-ups"],
	["Easy to spell", "Hard to spell"],
	["Ant-sized", "Elephant-sized"],
	["Library quiet", "Baraat loud"],
	["Idli soft", "Coconut hard"],
	["Bullock-cart slow", "Bullet-train fast"],
	["Useless", "Useful"],
	["Ugly", "Beautiful"],
	["Rare", "Common"],
	["Forgettable", "Unforgettable"],
	["Chappal casual", "Shaadi formal"],
	["Sunday-afternoon relaxed", "Board-exam stressful"],
	["Smells bad", "Smells amazing"],
	["Tastes bad", "Tastes amazing"],
	["Summer thing", "Winter thing"],
	["Indoor", "Outdoor"],
	["Introvert thing", "Extrovert thing"],
	["Mummy approves", "Mummy disapproves"],
	["Normal", "Weird"],
	["Cute", "Scary"],
	["Bad gift", "Great gift"],
	["Bad movie snack", "Great movie snack"],
	["Bad date idea", "Great date idea"],
	["Mainstream", "Niche"],
	["Overpriced", "Worth every rupee"],
	["Realistic", "Totally filmy"],
	["Bad wedding food", "Great wedding food"],
	["Worst Bollywood song", "Best Bollywood song"],
	["Weakling", "Baahubali"],
	["Short-lived", "Lasts forever"],
	["Easy to learn", "Hard to learn"],
	["Pure luck", "Pure skill"],
	["Simple", "Complicated"],
	["Cringe", "Cool"],
	["Ordinary", "Legendary"],
	["Bad in monsoon", "Perfect in monsoon"],
	["Bad road-trip snack", "Great road-trip snack"],
	["Fictional", "Real"],
	["Annoying", "Lovable"],
	["Worst movie ending", "Best movie ending"],
	["Bad pet", "Great pet"],
	["Nightmare job", "Dream job"],
	["Very desi", "Very foreign"],
	["Terrible sequel", "Better than original"],
	["Quick", "Takes forever"],
	["Weekday thing", "Weekend thing"],
	["Hated chore", "Fun chore"],
	["Dry", "Wet"],
	["Hill station calm", "Mumbai local chaos"],
	["Feather light", "Gas cylinder heavy"],
	["Fragile", "Nokia tough"],
	["Totally optional", "Absolutely essential"],
	["Worst pizza topping", "Best pizza topping"],
	["Worst ice cream flavour", "Best ice cream flavour"],
	["Bad breakfast", "Great breakfast"],
	["Bad holiday spot", "Dream holiday spot"],
	["Worst chai snack", "Best chai snack"],
	["Bad excuse", "Great excuse"],
	["Mood killer", "Mood booster"],
	["Light snack", "Full meal"],
	["Worst karaoke song", "Best karaoke song"],
	["Low stakes", "High stakes"],
	["Uncle vibes", "Gen Z vibes"],
	["Would never eat", "Would eat daily"],
	["Hate it", "Love it"],
	["Boring party", "Epic party"],
	["Easy to draw", "Hard to draw"],
	["Worst school subject", "Best school subject"],
	["Terrible roommate", "Perfect roommate"],
	["Awkward dance move", "Iconic dance move"],
	["Post-lunch sleepy", "Hyper after chai"],
	["Unlucky", "Lucky"],
	["Worst news", "Best news"],
	["Bad Sunday plan", "Perfect Sunday plan"],
	["Only in India", "Found everywhere"],
	["Not funny", "Hilarious"],
	["Serious", "Silly"],
	["Tiring", "Refreshing"],
	["Village life", "City life"],
	["Low maintenance", "High maintenance"],
	["Nobody knows it", "Everyone knows it"],
];
